### ISSUE TITLE
Android 10 will not work

### ISSUE THREAD

**Issue by linuxandria** [Magisk-Modules-Repo/bromitewebview#10]
As of this moment, neither Bromite nor upstream chromium have support for android 10.

Android 10 requires the webview to target sdk29 and upstream chromium has yet to do this, and it's uncertain if they ever will. For now the only webview that can be used is default AOSP webview or Google webview on any android 10 device

**Comment by alexa-v2** [comment]
See https://groups.google.com/a/chromium.org/forum/m/#!topic/android-webview-dev/Y8FIRqJCCNA

**Comment by hafizidev** [comment]
> See https://groups.google.com/a/chromium.org/forum/m/#!topic/android-webview-dev/Y8FIRqJCCNA

It says there that android 10 support already landed. Will we hear the good news soon?

**Comment by alexa-v2** [comment]
@hafizidev no, it says it'll land in stable v80

However, bromite still will need to integrate the changes too. Nevertheless it's coming :)

**Comment by linuxandria** [comment]
Resolved in 4.4.1
