### ISSUE TITLE
Overlay problems resulting in bootloops 

### ISSUE THREAD

**Issue by XspeedPL** [Magisk-Modules-Repo/bromitewebview#12]
There are two problems I found:
1. The `post-fs-data.sh` script breaks the `overlays.xml` file and makes Android flip itself out the window:
```xml
<item packageName="${OL}" userId="0" targetPackageName="android" baseCodePath="${DR}/treble-overlay-webview.apk" state="6" isEnabled="true" isStatic="true" priority="98" />
<item packageName="${OL}" userId="0" targetPackageName="android" baseCodePath="${DR}/treble-overlay-webview.apk" state="6" isEnabled="true" isStatic="true" priority="98" />
<item packageName="${OL}" userId="0" targetPackageName="android" baseCodePath="${DR}/treble-overlay-webview.apk" state="6" isEnabled="true" isStatic="true" priority="98" />
```
That's exactly what I found at the end of the file after bootlooping a few times.

2. After deleting the `post-fs-data.sh` completely, putting the overlay inside `/vendor/overlay/` and manually creating the `overlays.xml` entry I get this:
```
02-12 22:37:25.911  1397  1397 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-12 22:37:25.911  1397  1397 E AndroidRuntime: java.lang.IllegalArgumentException: State 6 is not a valid state
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at android.content.om.OverlayInfo.ensureValidState(OverlayInfo.java:141)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at android.content.om.OverlayInfo.<init>(OverlayInfo.java:111)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.OverlayManagerSettings$SettingsItem.getOverlayInfo(OverlayManagerSettings.java:493)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.OverlayManagerSettings$SettingsItem.-wrap0(Unknown Source:0)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.OverlayManagerSettings.-com_android_server_om_OverlayManagerSettings-mthref-1(OverlayManagerSettings.java:177)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.-$Lambda$VuwDBWerAG9B6xB4Rr4-FeDL3jk$1.$m$0(Unknown Source:2)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.-$Lambda$VuwDBWerAG9B6xB4Rr4-FeDL3jk$1.apply(Unknown Source:0)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:194)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:501)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.OverlayManagerSettings.getOverlaysForUser(OverlayManagerSettings.java:176)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.OverlayManagerServiceImpl.updateOverlaysForUser(OverlayManagerServiceImpl.java:89)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.OverlayManagerService.onSwitchUser(OverlayManagerService.java:314)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.om.OverlayManagerService.<init>(OverlayManagerService.java:280)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:681)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:163)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:304)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:78)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:416)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:282)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
02-12 22:37:25.911  1397  1397 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
02-12 22:37:25.912  1397  1397 I Process : Sending signal. PID: 1397 SIG: 9
```
Which also effectively kills the system every time it tries to start.

Device: Xperia X
Android: 8.0.0
ROM: Stock (Sony)

**Comment by linuxandria** [comment]
Sed is apparently not passing the arguments (variables) correctly

It is worth noting that you are so far the only one with this issue out of the 504 in my telegram group

**Comment by XspeedPL** [comment]
Apparently it is not.
I am more interested in the "state 6" error, none of the other entries in my `overlays.xml` have that value, where does it come from?

I am using Magisk 20.3, and it also might be worth noting I use the Busybox module by osm0sis.
If I can provide any other information or help in any other way let me know.

**Comment by linuxandria** [comment]
That "state 6" is definitely valid. Works ok on every device tested and talking with @Skittles9823 it should definitely be ok

Why you're system rejects it I have no idea. Probably w change by Sony's theming engine

Nonetheless I will release a beta on telegram with a fix for the variables not being passed on

**Comment by skittles9823** [comment]
Yea state="6" is valid on every device I've seen.

If it's not valid then the system should be creating its own entry in overlays.xml anyway.

**Comment by XspeedPL** [comment]
Well, here are the contents of my `overlays.xml` if you're interested: [pastebin link](https://pastebin.com/JRwRGER1).

**Comment by linuxandria** [comment]
@skittles9823 his default seems to be "3" not "6*

What's the difference and will "3" work on other ROMs?

**Comment by skittles9823** [comment]
@linuxandria 
> What's the difference and will "3" work on other ROMs?

Honestly I'm not sure. You'd have to look and see if there is documentation on the different overlay states.

**Comment by linuxandria** [comment]
@skittles9823 lol o can't find anything related to RRO is AOSP docs and there's only one very dumbed down sony page o was given a link to forever ago

**Comment by skittles9823** [comment]
Yea ikr. If I manage to dig something up I'll let you know.

**Comment by XspeedPL** [comment]
@linuxandria @skittles9823 I did some research.
States above 3 were only introduced in SDK 28. SDK 27 and before had only up to state 3.

Look here for reference, states are well documented:
[OverlayInfo (SDK 27)](https://github.com/elastic/AndroidSDKMirror-27/blob/master/android/content/om/OverlayInfo.java)
[OverlayInfo (SDK 28)](https://github.com/elastic/AndroidSDKMirror-28/blob/master/android/content/om/OverlayInfo.java)

**Comment by skittles9823** [comment]
@XspeedPL ahh. That's actually great to know and will be quite easy to fix then.

**Comment by linuxandria** [comment]
@skittles9823 so will state 3 work correctly on devices that support state 6?

**Comment by skittles9823** [comment]
That I'm not sure. You would have to test it.

If you could add a version check and set the state depending on android version in a variable.

**Comment by linuxandria** [comment]
@XspeedPL try the latest alpha @ https://github.com/linuxandria/bromitewebview/releases

**Comment by XspeedPL** [comment]
I just flashed it, but the sed didn't do anything this time. My xml file has no new entries.

**Comment by linuxandria** [comment]
Magisk can't magic mount over /data

Is it working tho? I mean is it selectable

**Comment by linuxandria** [comment]
Please check version 4.4.3 out in magisk manager now

**Comment by linuxandria** [comment]
Resolved in latest stable.

In addition in case of breakage, overlays.xml is copied to /sdcard/bromite during install

Closing
