### ISSUE TITLE
Installation of Bromite WebView module breaks SafetyNet ctsProfile and basicIntegrity, even if module is disabled.

### ISSUE THREAD

**Issue by darylrobert** [Magisk-Modules-Repo/bromitewebview#15]
Reproducing steps:
1. Wipe clean phone
2. Reboot with unlocked bootloader, stock boot.img
3. Run SafetyNet attestation, ctsProfile and basicIntegrity passes
4. Install Magisk-v20.3.zip through TWRP, reboot and run Magisk Manager SafetyNet check (Magisk Manager not hidden & repackaged yet), ctsProfile and basicIntegrity passes
5. Install magisk-riru-core-v19.7.zip through Magisk Manager, reboot and run Magisk Manager SafetyNet check, ctsProfile and basicIntegrity passes
6. Install EdXposed-SandHook-v0.4.6.1.4510.-release.zip through Magisk Manager (not hidden & repackaged yet), reboot and run Magisk Manager SafetyNet check, ctsProfile and basicIntegrity still passes.
7. Install EdXposed Manager, enable Settings > App List mode and Settings > Pass SafetyNet, reboot and run Magisk Manager SafetyNet check, ctsProfile and basicIntegrity still passes.
8. Install bwv_5.0.0-alpha2.zip through Magisk Manager with /sdcard/bromite/webview.apk existing already due to GitHub slow download speed , reboot and run Magisk Manager SafetyNet check, ctsProfile and basicIntegrity now both fails.
9. Reboot to twrp-3.3.1-1-ginkgo.img, then install zip bwv_5.0.0-alpha2.zip so it uninstalls Bromite WebView, reboot and run Magisk Manager SafetyNet check, ctsProfile and basicIntegrity returns to both passing again.

Reproducting information:
Redmi Note 8 (ginkgo)
ROM: xiaomi.eu_multi_HMNote8_V11.0.5.0.PCOCNXM_v11-9.zip
Android version: 9 PKQ1.190616.001
Android security patch level: 2020-01-01

[bromitewebview-debug.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/4364758/bromitewebview-debug.log)

**Comment by linuxandria** [comment]
Unable to reproduce.

Also not possible, the module neither modifies any cts relevant props nor touches /system

**Comment by linuxandria** [comment]
Besides the fact you installed Xposed as well, my module has never caused said issue.

In EdXposed manager setting there is an option to pass safetynet, check it
