### ISSUE TITLE
Overheating device after install !

### ISSUE THREAD

**Issue by EvoXCX** [Magisk-Modules-Repo/bromitewebview#17]
Hi,
My device begin to overheat after install this module I'm on LineageOS last version on OnePlus 6

**Comment by EvoXCX** [comment]
- Copying zip to temp directory
- Installing Bromite_Systemless_Webview-6.1.1(3124).zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/.tsgp.cdu.kvmn.mm/cache/flash/install.zip
  inflating: module.prop
****************************
 Bromite Systemless Webview 
 by Alexandria C 
****************************
Archive:  /data/user/0/.tsgp.cdu.kvmn.mm/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Debug mode
  Module install log will include debug info
  It's in /sdcard/bromite/logs
- Extracting module files
- Removing old files
- Installing
- arm64 SDK 29 system detected, selecting the appropriate files
- Testing internet connectivity
- Awesome, you have internet
- Testing internet connectivity
- Downloading extra files please be patient...
 Verifying files...
 Verified successfully. Proceeding...
/data/user/0/.tsgp.cdu.kvmn.mm/cache/flash
- Extracting downloaded file
 Android 10 or later detected
- Cleaning up...
- Backing up important stuffs to module directory
 !!!!!!!!!!!!!!! VERY IMPORTANT PLEASE READ !!!!!!!!!!!!!!!!!
 Reboot immediately after flashing or you may experience some issues! 
 Also, if you had any other webview such as Google webview, you may re-enable
 But beware conflicts
 Next boot may take significantly longer, we have to clear Dalvik cache here
  
	  / _ )  ____ ___   __ _   (_) / /_ ___                 
	 / _  | / __// _ \ /  ' \ / / / __// -_)                
	/____/ /_/   \___//_/_/_//_/  \__/ \__/                 
	
	   ____              __                __               
	  / __/  __ __  ___ / /_ ___   __ _   / / ___   ___  ___
	 _\ \   / // / (_-</ __// -_) /  ' \ / / / -_) (_-< (_-<
	/___/   \_, / /___/\__/ \__/ /_/_/_//_/  \__/ /___//___/
	       /___/                                            
	  _      __        __          _                        
	 | | /| / / ___   / /  _  __  (_) ___  _    __          
	 | |/ |/ / / -_) / _ \| |/ / / / / -_)| |/|/ /          
	 |__/|__/  \__/ /_.__/|___/ /_/  \__/ |__,__/           
	                                                        
 Enjoy a more private and faster webview, done systemlessly
 Don't forget my links:
 Social platforms:
  https://t.me/alexiadev, https://discord.gg/gTnDxQ6
 Donate at:
  https://paypal.me/linuxandria
  https://www.patreon.com/linuxandria_xda
- All commands ran successfully please reboot
 
 
- Setting Permissions
 
    **************************************
    *   MMT Extended by Zackptg5 @ XDA   *
    *      Modified by Alexandria        *
    **************************************
 
- Done

**Comment by EvoXCX** [comment]
[logs.zip](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5277682/logs.zip)

**Comment by unixandria-xda** [comment]
This is a very well known issue with any module that overlays files in /product, specifically ones that place overlays there.

The issue is not with the module but with Google Play Services. 

To solve make sure only the unstable part of the app is hidden in magisk hide
