### ISSUE TITLE
Problems after installing bromitewebview module on MIUI 12 (Google Webview can't be updated)

### ISSUE THREAD

**Issue by catfluoride** [Magisk-Modules-Repo/bromitewebview#19]
Hi. I installed your module on my MIUI 12 phone. Since then, I'm unable to update webview from the play store, as I keep getting a "apps is not compatible" message. This happens even after the module is uninstalled and the phone is rebooted.

I read after installing that result on MIUI are a mixed bag (my bad)...

I guess there are remnants of the module somewhere that make google webview "incompatible". Can someone give me any suggestion on how to solve this?

Thanks a lot in advance.

**Comment by unixandria-xda** [comment]
MIUI has a certain habit of messing with things they shouldn't. It's not my fault that somehow they broke google webview if any other is installed. I can't and won't test on MIUI, but I've had mixed reporting of it working or not working.

You may have to factory reset. Closing this issue as it's out of my control.

**Comment by catfluoride** [comment]
Hi, @unixandria-xda . Thanks for replying
Of course, I didn't mean to blame you for this. I know that MIUI is a bit... let's say... weird...
I was just looking for info.

Thanks a lot anyway :-)
