### ISSUE TITLE
Boot loop after installing BromiteWebView from Magisk

### ISSUE THREAD

**Issue by iyesin** [Magisk-Modules-Repo/bromitewebview#2]
**Bromite version**

Version: `77.0.3865.81`
Arch: `arm64`
Android version: `8.0`
Device model: `Xiaomi/omni_gemini/gemini:7.1.2/NJH47F`

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
I have no idea. I just updated BromiteWebView from Magisk.

**Is the bug a crash?**
Since it is boot loop, I can't provide you logcat data.

**Describe the bug**
Very slow boot logo for about 10 minutes, reboot and recovery menu

**To Reproduce**

1. Go to Magisk modules
2. Click find updated BromiteWebView
3. Click update
4. Agree to reboot
5. Get boot loop

**Expected behavior**
Work like nothing changed

**Comment by alexa-v2** [comment]
Install the log catcher module as well and reb

Logs will be in /data/local/boot

Then report back with logs

**Comment by iyesin** [comment]
@alexa-v2 how can I install it if my phone is dead? I can only get to recovery.

**Comment by alexa-v2** [comment]
You could, you know download to pc, transfer to phone and flash in TWRP?
________________________________

**Comment by iyesin** [comment]
Since almost every dynamic (non-static) binary crashing even in my recovery console, I suspect it's either HW failure or Magisk-beta was wrong choice for non-development phone.

**Comment by alexa-v2** [comment]
Seeing as this module is not supported to be flashed in recovery . . . .
