### ISSUE TITLE
Request: Give more info about how overlays can be shared

### ISSUE THREAD

**Issue by m-rey** [Magisk-Modules-Repo/bromitewebview#20]
> MIUI is not officially supported unless someone is willing to share the overlays used in MIUI. 

How could someone potentially do this? I guess there are many users that would like to use it on MIUI and are willing to contribute. However, they don't know how to do so. Please add some info about how this could be done. Alternatively just link to some resources that explain how it is done.

**Comment by unixandria-xda** [comment]
Mainly I need to know the package names of apps that start with com.miui or have overlay in the name, because at one point an user reported disabling a certain one does the trick but never mentioned which one

**Comment by m-rey** [comment]
Sure thing. I'm using a Xiaomi Mi Note 10 Pro (tucana), with `Android 10 QKQ1.190825.002` and MIUI version `MIUI by xiaomi.eu 12.0.2.0 (QFDCNXM)`. Here's the info you requested. I hope it helps:

> package names of apps that start with com.miui

* `adb shell cmd package list packages | cut -f 2 -d ":" | grep "^com.miui"`:
```
com.miui.screenrecorder
com.miui.powerkeeper
com.miui.fm
com.miui.contentcatcher
com.miui.packageinstaller
com.miui.extraphoto
com.miui.securityadd
com.miui.gallery
com.miui.securitycenter
com.miui.videoplayer
com.miui.guardprovider
com.miui.backup
com.miui.notification
com.miui.micloudsync
com.miui.daemon
com.miui.huanji
com.miui.vsimcore
com.miui.securitycore
com.miui.phrase
com.miui.player
com.miui.miservice
com.miui.system
com.miui.catcherpatch
com.miui.systemui.devices.overlay
com.miui.compass
com.miui.aod
com.miui.cit
com.miui.rom
com.miui.vpnsdkmanager
com.miui.personalassistant
com.miui.misound
com.miui.bugreport
com.miui.documentsuioverlay
com.miui.cloudbackup
com.miui.mishare.connectivity
com.miui.freeform
com.miui.miwallpaper.mars
com.miui.nextpay
com.miui.notes
com.miui.cloudservice
com.miui.touchassistant
com.miui.miwallpaper.earth
com.miui.calculator
com.miui.cloudservice.sysbase
com.miui.miwallpaper
com.miui.cleanmaster
com.miui.weather2
com.miui.accessibility
com.miui.systemui.carriers.overlay
com.miui.systemui.overlay.devices.android
com.miui.smsextra
com.miui.fmservice
com.miui.newmidrive
com.miui.core
com.miui.face
com.miui.home
com.miui.audioeffect
```


> overlay in the name

* `adb shell cmd package list packages | cut -f 2 -d ":" | grep "overlay"`:
```
com.google.android.overlay.gmsgsaconfig
com.android.systemui.icon.overlay
com.qualcomm.qti.optinoverlay
com.google.android.overlay.modules.permissioncontroller
android.qvaoverlay.common
com.android.settings.overlay.miui
android.overlay.common
com.android.systemui.notch.overlay
android.miui.overlay
android.overlay.target
com.miui.systemui.devices.overlay
com.google.android.overlay.modules.ext.services
com.android.systemui.gesture.line.overlay
com.miui.documentsuioverlay
com.android.systemui.overlay.miui
com.google.android.overlay.gmsconfig
com.android.phone.overlay.common
com.android.carrierconfig.overlay.common
android.aosp.overlay
com.android.systemui.overlay.common
com.android.server.telecom.overlay.common
com.google.android.overlay.modules.permissioncontroller.forframework
com.android.systemui.navigation.bar.overlay
com.miui.systemui.carriers.overlay
com.miui.systemui.overlay.devices.android
com.xiaomi.bluetooth.overlay
com.android.cellbroadcastreceiver.overlay.common
com.android.bluetooth.overlay.common
```

**Comment by unixandria-xda** [comment]
My two primary suspects are android.miui.overlay and com.miui.systemui.devices.overlay

Could you share the APKs?

**Comment by m-rey** [comment]
Sure.
android.miui.overlay: https://cloud.0x90.space/s/WL0BikF4ZZFTAJz

com.miui.systemui.devices.overlay: https://cloud.0x90.space/s/CiRw7xn3PP9djVo

Both links expire on 31.12.2020, so please make sure to grab the files until then.

**Comment by unixandria-xda** [comment]
> Sure.
> 
> android.miui.overlay: https://cloud.0x90.space/s/198mS71fFKUdqo4
> 
> com.miui.systemui.devices.overlay: https://cloud.0x90.space/s/fu8erzAuaMt7ePh
> 
> Both links expire on 01.02.2021, so please make sure to grab the files until then.

Can you re-upload both to file.io? File.io is much more CLI friendly

**Comment by m-rey** [comment]
Note that the urls expire in 60 days (or after download) :

* android.miui.overlay: https://file.io/TnwDUsGSrAQP
* com.miui.systemui.devices.overlay: https://file.io/gQUcHgyWS0Ws

**Comment by m-rey** [comment]
Both files got deleted. Is it because you downloaded them?

If you didn't, please either use the URLs I posted before. Alternatively, please tell me how I should best send you some new file.io URLs to the requested files privately.

**Comment by androidacy** [comment]
Can you try 8.1.0 beta 3 from dl.androidacy.com?

**Comment by m-rey** [comment]
I now use a custom rom that is not based on MIUI, so I won't be able to test whether it works on MIUI.

**Comment by androidacy** [comment]
Ah, okay

**Comment by androidacy** [comment]
We have at least one report that it does now, so I'll close this issue
