### ISSUE TITLE
Permission denied to copy default config to /sdcard/WebviewSwitcher/config.txt

### ISSUE THREAD

**Issue by GitGangGuy** [Magisk-Modules-Repo/bromitewebview#22]
I'm running ProtonAOSP on a Pixel 5 with Android 11. I saw from #18 that you don't have access to an Android 11 phone yet and therefore can't test it, which I understand. However, it would be awesome if you could still look into this.

The installation from within the newest Magisk Manager (canary) fails. I went through the debug logs and found that for some reason the permission to copy the default config (from `/data/adb/modules_update/bromitewebview/config.txt`) to `/sdcard/WebviewSwitcher/config.txt` is being denied. I'm ok with the default config (just want to replace the default android webview with the bromite one) so it's strange to see this fail. I tried to copy the file myself in a root adb shell and it wouldn't allow me to do so either - manually writing the file in `vi` fails too (how come root doesn't have the permission to add a file to a directory that belongs to root?!). I tried deleting the `/sdcard/WebviewSwitcher` directory, but I'm getting an error: `rm: install.log: Math result not representable`. I also tried changing the folder access permissions to my user (`u0_a193`), but it wouldn't change anything. Is that folder part of magisk/the overlay fs in some way and that's why I can't access it? Not sure how I should go about this, I can't add a custom `config.txt` nor can I use the default one...

**Comment by GitGangGuy** [comment]
Oops, forgot the debug log:
```
+ ui_print '- Extracting module files'
+ true
+ echo '- Extracting module files'
+ unzip -o /data/user/0/occ.qhbj/cache/flash/install.zip -x 'META-INF/*' common/functions.sh -d /data/adb/modules_update/bromitewebview
Archive:  /data/user/0/occ.qhbj/cache/flash/install.zip
  inflating: .gitattributes
   creating: .github/
  inflating: .github/FUNDING.yml
   creating: .github/workflows/
  inflating: .github/workflows/greetings.yml
  inflating: .gitignore
   creating: .vscode/
  inflating: .vscode/settings.json
  inflating: CHANGELOG.md
  inflating: LICENSE
  inflating: README.md
  inflating: SECURITY.md
   creating: common/
  inflating: common/install.sh
   creating: common/overlay10/
  inflating: common/overlay10/AndroidManifest.xml
   creating: common/overlay10/res/
   creating: common/overlay10/res/xml/
  inflating: common/overlay10/res/xml/config_webview_packages.xml
   creating: common/overlay9/
  inflating: common/overlay9/AndroidManifest.xml
   creating: common/overlay9/res/
   creating: common/overlay9/res/xml/
  inflating: common/overlay9/res/xml/config_webview_packages.xml
   creating: common/tools/
  inflating: common/tools/aapt-arm
  inflating: common/tools/aapt-arm64
  inflating: common/tools/aapt-x86
  inflating: common/tools/aapt-x86_64
  inflating: common/tools/aria2c-arm
  inflating: common/tools/aria2c-arm64
  inflating: common/tools/aria2c-x86
  inflating: common/tools/aria2c-x86_64
  inflating: common/tools/zipsigner
  inflating: common/tools/zipsigner-3.0-dexed.jar
  inflating: config.txt
  inflating: customize.sh
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: sepolicy.rule
  inflating: service.sh
   creating: system/
  inflating: system/placeholder
  inflating: uninstall.sh
+ '[' -f /data/adb/modules_update/bromitewebview/common/addon.tar.xz ]
+ ls -A '/data/adb/modules_update/bromitewebview/common/addon/*/install.sh'
+ '['  ]
+ ui_print '- Removing old files'
+ true
+ echo '- Removing old files'
+ '[' -f /data/adb/modules/.bromitewebview-files ]
+ ui_print '- Installing'
+ true
+ echo '- Installing'
+ test -d /data/adb/modules/bromitewebview
+ '[' -f /data/adb/modules_update/bromitewebview/common/install.sh ]
+ . /data/adb/modules_update/bromitewebview/common/install.sh
+ mkdir /data/adb/modules_update/bromitewebview/logs
+ TRY_COUNT=0
+ VERSIONFILE=/sdcard/WebviewSwitcher/version
+ alias 'aapt="$MODPATH"/common/tools/aapt-"$ARCH"'
+ alias 'sign="$MODPATH"/common/tools/zipsigner'
+ chmod -R 0755 /data/adb/modules_update/bromitewebview/common/tools
+ test -f /sdcard/bromite
+ test '!' -d /sdcard/WebviewSwitcher
+ VEN=/system/vendor
+ '[' -L /system/vendor ]
+ VEN=/vendor
+ '[' -f /vendor/build.prop ]
+ export 'BUILDS=/system/build.prop /vendor/build.prop'
+ ui_print '- arm64 SDK 30 system detected, selecting the appropriate files'
+ true
+ echo '- arm64 SDK 30 system detected, selecting the appropriate files'
+ test 0 -ge 5
+ do_install
+ set_config
+ ui_print '- Setting configs...'
+ true
+ echo '- Setting configs...'
+ ui_print '- Make sure if you want/need a custom setup to edit config.txt and reflash'
+ true
+ echo '- Make sure if you want/need a custom setup to edit config.txt and reflash'
+ test -f /sdcard/WebviewSwitcher/config.txt
+ ui_print '- No config found, using defaults'
+ true
+ echo '- No config found, using defaults'
+ cp /data/adb/modules_update/bromitewebview/config.txt /sdcard/WebviewSwitcher
cp: can't create '/sdcard/WebviewSwitcher/config.txt': Permission denied
+ . /sdcard/WebviewSwitcher/config.txt
update-binary: .: line 64: can't open '/sdcard/WebviewSwitcher/config.txt': No such file or directory
```

**Comment by AnFlare** [comment]
Same here.
Android 7.0, same error in the end.

`+ ui_print '- Extracting module files'
+ true
+ echo '- Extracting module files'
+ unzip -o /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip -x 'META-INF/*' common/functions.sh -d /data/adb/modules_update/bromitewebview
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: .gitattributes
   creating: .github/
  inflating: .github/FUNDING.yml
   creating: .github/workflows/
  inflating: .github/workflows/greetings.yml
  inflating: .gitignore
  inflating: CHANGELOG.md
  inflating: LICENSE
  inflating: README.md
  inflating: SECURITY.md
   creating: common/
  inflating: common/install.sh
   creating: common/overlay10/
  inflating: common/overlay10/AndroidManifest.xml
   creating: common/overlay10/res/
   creating: common/overlay10/res/xml/
  inflating: common/overlay10/res/xml/config_webview_packages.xml
   creating: common/overlay9/
  inflating: common/overlay9/AndroidManifest.xml
   creating: common/overlay9/res/
   creating: common/overlay9/res/xml/
  inflating: common/overlay9/res/xml/config_webview_packages.xml
   creating: common/tools/
  inflating: common/tools/aapt-arm
  inflating: common/tools/aapt-arm64
  inflating: common/tools/aapt-x86
  inflating: common/tools/aapt-x86_64
  inflating: common/tools/aria2c-arm
  inflating: common/tools/aria2c-arm64
  inflating: common/tools/aria2c-x86
  inflating: common/tools/aria2c-x86_64
  inflating: common/tools/zipsigner
  inflating: common/tools/zipsigner-3.0-dexed.jar
  inflating: config.txt
  inflating: customize.sh
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: sepolicy.rule
  inflating: service.sh
   creating: system/
  inflating: system/placeholder
  inflating: uninstall.sh
+ '[' -f /data/adb/modules_update/bromitewebview/common/addon.tar.xz ]
+ ls -A '/data/adb/modules_update/bromitewebview/common/addon/*/install.sh'
+ '['  ]
+ ui_print '- Removing old files'
+ true
+ echo '- Removing old files'
+ '[' -f /data/adb/modules/.bromitewebview-files ]
+ ui_print '- Installing'
+ true
+ echo '- Installing'
+ test -d /data/adb/modules/bromitewebview
+ '[' -f /data/adb/modules_update/bromitewebview/common/install.sh ]
+ . /data/adb/modules_update/bromitewebview/common/install.sh
+ mkdir /data/adb/modules_update/bromitewebview/logs
+ TRY_COUNT=0
+ VERSIONFILE=/sdcard/WebviewSwitcher/version
+ alias 'aapt="$MODPATH"/common/tools/aapt-"$ARCH"'
+ alias 'sign="$MODPATH"/common/tools/zipsigner'
+ chmod -R 0755 /data/adb/modules_update/bromitewebview/common/tools
+ test -f /sdcard/bromite
+ test '!' -d /sdcard/WebviewSwitcher
+ VEN=/system/vendor
+ '[' -L /system/vendor ]
+ '[' -f /system/vendor/build.prop ]
+ BUILDS=/system/build.prop
+ ui_print '- arm SDK 24 system detected, selecting the appropriate files'
+ true
+ echo '- arm SDK 24 system detected, selecting the appropriate files'
+ test 0 -ge 5
+ do_install
+ set_config
+ ui_print '- Setting configs...'
+ true
+ echo '- Setting configs...'
+ ui_print '- Make sure if you want/need a custom setup to edit config.txt and reflash'
+ true
+ echo '- Make sure if you want/need a custom setup to edit config.txt and reflash'
+ test -f /sdcard/WebviewSwitcher/config.txt
+ ui_print '- No config found, using defaults'
+ true
+ echo '- No config found, using defaults'
+ cp /data/adb/modules_update/bromitewebview/config.txt /sdcard/WebviewSwitcher
cp: can't create '/sdcard/WebviewSwitcher/config.txt': Permission denied
+ . /sdcard/WebviewSwitcher/config.txt
update-binary: .: line 64: can't open '/sdcard/WebviewSwitcher/config.txt': No such file or directory
`

**Comment by unixandria-xda** [comment]
Issue should be resolved in latest update. Please let me know if it isn't

**Comment by NYCJames** [comment]
Hi,

I am also getting this error trying to install the latest version.

I have a Pixel 4a 5G running latest Android 11.

`+ ui_print '- Extracting module files'
+ true
+ echo '- Extracting module files'
+ unzip -o /data/user/0/nds.vvsczmstc/cache/flash/install.zip -x 'META-INF/*' common/functions.sh -d /data/adb/modules_update/bromitewebview
Archive:  /data/user/0/nds.vvsczmstc/cache/flash/install.zip
  inflating: .gitattributes
   creating: .github/
  inflating: .github/FUNDING.yml
   creating: .github/workflows/
  inflating: .github/workflows/greetings.yml
  inflating: .gitignore
  inflating: CHANGELOG.md
  inflating: LICENSE
  inflating: README.md
  inflating: SECURITY.md
   creating: common/
  inflating: common/install.sh
   creating: common/overlay10/
  inflating: common/overlay10/AndroidManifest.xml
   creating: common/overlay10/res/
   creating: common/overlay10/res/xml/
  inflating: common/overlay10/res/xml/config_webview_packages.xml
   creating: common/overlay9/
  inflating: common/overlay9/AndroidManifest.xml
   creating: common/overlay9/res/
   creating: common/overlay9/res/xml/
  inflating: common/overlay9/res/xml/config_webview_packages.xml
   creating: common/tools/
  inflating: common/tools/aapt-arm
  inflating: common/tools/aapt-arm64
  inflating: common/tools/aapt-x86
  inflating: common/tools/aapt-x86_64
  inflating: common/tools/aria2c-arm
  inflating: common/tools/aria2c-arm64
  inflating: common/tools/aria2c-x86
  inflating: common/tools/aria2c-x86_64
  inflating: common/tools/zipsigner
  inflating: common/tools/zipsigner-3.0-dexed.jar
  inflating: config.txt
  inflating: customize.sh
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: sepolicy.rule
  inflating: service.sh
   creating: system/
  inflating: system/placeholder
  inflating: uninstall.sh
+ '[' -f /data/adb/modules_update/bromitewebview/common/addon.tar.xz ]
+ ls -A '/data/adb/modules_update/bromitewebview/common/addon/*/install.sh'
+ '['  ]
+ ui_print '- Removing old files'
+ true
+ echo '- Removing old files'
+ '[' -f /data/adb/modules/.bromitewebview-files ]
+ ui_print '- Installing'
+ true
+ echo '- Installing'
+ test -d /data/adb/modules/bromitewebview
+ '[' -f /data/adb/modules_update/bromitewebview/common/install.sh ]
+ . /data/adb/modules_update/bromitewebview/common/install.sh
+ mkdir /data/adb/modules_update/bromitewebview/logs
+ TRY_COUNT=0
+ VERSIONFILE=/storage/emulated/0/WebviewSwitcher/version
+ alias 'aapt="$MODPATH"/common/tools/aapt-"$ARCH"'
+ alias 'sign="$MODPATH"/common/tools/zipsigner'
+ chmod -R 0755 /data/adb/modules_update/bromitewebview/common/tools
+ test -f /storage/emulated/0/bromite
+ test '!' -d /storage/emulated/0/WebviewSwitcher
+ magiskpolicy --live 'allow system_server untrusted_app_25_devpts chr_file { read write }'
Load policy from: /sys/fs/selinux/policy
target type untrusted_app_25_devpts does not exist
Error in: allow system_server untrusted_app_25_devpts chr_file read
target type untrusted_app_25_devpts does not exist
Error in: allow system_server untrusted_app_25_devpts chr_file write
+ magiskpolicy --live 'allow system_server sdcardfs file { read write }'
Load policy from: /sys/fs/selinux/policy
+ magiskpolicy --live 'allow zygote adb_data_file file getattr'
Load policy from: /sys/fs/selinux/policy
+ VEN=/system/vendor
+ '[' -L /system/vendor ]
+ VEN=/vendor
+ '[' -f /vendor/build.prop ]
+ export 'BUILDS=/system/build.prop /vendor/build.prop'
+ ui_print '- arm64 SDK 30 system detected, selecting the appropriate files'
+ true
+ echo '- arm64 SDK 30 system detected, selecting the appropriate files'
+ test 0 -ge 5
+ do_install
+ set_config
+ ui_print '- Setting configs...'
+ true
+ echo '- Setting configs...'
+ ui_print '- Make sure if you want/need a custom setup to edit config.txt and reflash'
+ true
+ echo '- Make sure if you want/need a custom setup to edit config.txt and reflash'
+ test -f /storage/emulated/0/WebviewSwitcher/config.txt
+ ui_print '- No config found, using defaults'
+ true
+ echo '- No config found, using defaults'
+ cp /data/adb/modules_update/bromitewebview/config.txt /storage/emulated/0/WebviewSwitcher
cp: can't create '/storage/emulated/0/WebviewSwitcher/config.txt': Permission denied
+ . /storage/emulated/0/WebviewSwitcher/config.txt
/data/user/0/nds.vvsczmstc/cache/flash/update-binary: .: line 68: can't open '/storage/emulated/0/WebviewSwitcher/config.txt': No such file or directory
`

**Comment by GitGangGuy** [comment]
I'm not running root anymore, so I can't comment on the recent changes. Thanks for looking into it! @androidacy
