### ISSUE TITLE
[BUG] post-fs-data.sh invokes duplicate entries in overlays.xml

### ISSUE THREAD

**Issue by didierm** [Magisk-Modules-Repo/bromitewebview#23]
Each device restarts invokes an extra **<item packageName="com.linuxandria.WebviewOverlay" ...>** entry in /data/system/overlays.xml.

This is probably due to : 
https://github.com/Magisk-Modules-Repo/bromitewebview/blob/21c175b0af904164f531db0377c31c36ace9ca27/post-fs-data.sh#L34
which should read : 
```
if grep 'com.linuxandria.WebviewOverlay' /data/system/overlays.xml ;
```

**Comment by unixandria-xda** [comment]
Issue fixed in latest stable. Please report back if it persists.
