### ISSUE TITLE
[BUG] uninstall.sh does not cope for all WebviewOverlay items in overlays.xml

### ISSUE THREAD

**Issue by didierm** [Magisk-Modules-Repo/bromitewebview#24]
Not sure whether it is due to my setup (generic LOS17.1 + Work profile, invoked by Insular (which is a Google-free Island clone)), but my overlays.xml entries look like this : 
```
    <item packageName="com.linuxandria.WebviewOverlay" userId="10" targetPackageName="android" baseCodePath="/product/overlay/WebviewOverlay.apk" state="6" isEnabled="true" isStatic="true" priority="998" />
    <item packageName="com.linuxandria.WebviewOverlay" userId="0" targetPackageName="android" baseCodePath="/product/overlay/WebviewOverlay.apk" state="6" isEnabled="true" isStatic="true" priority="998" />
```
Note the : 
* multiple entries (for each user/profile)
* the peculiar priority (different from 98).

The uninstall script, however, is very specific : 
https://github.com/Magisk-Modules-Repo/bromitewebview/blob/21c175b0af904164f531db0377c31c36ace9ca27/uninstall.sh#L21

To cope with other cases, I'd suggest replacing the search pattern with : 
```
sed -i "/item packageName=\"${OL}\"/d" $LIST
```

**Comment by unixandria-xda** [comment]
Issue fixed in latest stable. Please report back if it persists.
