### ISSUE TITLE
Internet connectivity check is hardcoded to bing.com

### ISSUE THREAD

**Issue by didierm** [Magisk-Modules-Repo/bromitewebview#25]
During the module installation process, the arbitrary `bing.com` host is hardcoded for ping-checking internet connectivity : 
 https://github.com/Magisk-Modules-Repo/bromitewebview/blob/21c175b0af904164f531db0377c31c36ace9ca27/common/install.sh#L92

Standard Wi-Fi captive portal detection in Android uses **connectivitycheck.gstatic.com** .
I would like to suggest using this host (possibly by variable assignment) : 
```
...
#CONNECTIVITYHOST='1.1.1.1'
CONNECTIVITYHOST='connectivitycheck.gstatic.com'
...
  (ping -q -c 3 -W 1 "$CONNECTIVITYHOST" >/dev/null 2>&1) && return 0 || return 1
...
```

**Comment by unixandria-xda** [comment]
I prefer not to ping google services in my module.

Closing as invalid

**Comment by didierm** [comment]
I (think I) fully understand.
I am not sure whether bing.com is a viable alternative.

Would you not consider **one.one.one.one** (Cloudflare/APNIC) a nice middle-of-the-road solution ?
(unfortunately, www.un.org does not return pings)

**Comment by Iron-E** [comment]
I definitely think there's a better alternative to bing here. Users that wouldn't want to ping Google certainly wouldn't want to MS ping either. Or Apple, Facebook, Twitter— anything privacy-insensitive.

Like the other user suggested, something more neutral would be good.
