### ISSUE TITLE
[BUG] OFFLINE=true parameter is ignored during installation

### ISSUE THREAD

**Issue by didierm** [Magisk-Modules-Repo/bromitewebview#26]
Due to the program flow in
https://github.com/Magisk-Modules-Repo/bromitewebview/blob/21c175b0af904164f531db0377c31c36ace9ca27/common/install.sh#L412
, the **OFFLINE=true** parameter in **/sdcard/WebviewSwitcher/config.txt** is ignored : 
* ignoring the explicit `OFFLINE=true` parameter, newer apk's are downloaded and installed from the Bromite git repository ;
* Bromite git repository internet downloads are always attempted, even when in recovery mode.

To cope with these issues, I'd suggest changing the logic flow : 

1. if in recovery mode, do not attempt to go online ;
2. if OFFLINE=true, do not attempt to go online ;
3. in all other cases, attempt to go online.

```
do_install () {
  set_config
	if test ! "$BOOTMODE"
	then
		ui_print "- Detected recovery install! Falling back to offline install!"
		ui_print "- Please note you may encounter issues with this method"
		recovery_actions
		offline_install
		recovery_cleanup
		do_cleanup ;
	elif $OFFLINE
	then
		offline_install
		do_cleanup ;
	else
		test_connection
		if test $? -ne 0 ;
		then
			ui_print "- No internet detected, attempting offline install"
			offline_install
			do_cleanup ;
		else
			if test ${TRY_COUNT} -ge 5
			then
				it_failed ;
			else
				online_install ;
			fi
		fi
	fi
}
```

**Comment by unixandria-xda** [comment]
This should be fixed in latest stable. Please report if it doesn't
