### ISSUE TITLE
[ISSUE] Non-matching signatures prevent successful deployment

### ISSUE THREAD

**Issue by didierm** [Magisk-Modules-Repo/bromitewebview#27]
### Issue
After successfully installing the module and rebooting, an error occurs when installing **webview.apk** during execution of service.sh : 
https://github.com/Magisk-Modules-Repo/bromitewebview/blob/21c175b0af904164f531db0377c31c36ace9ca27/service.sh#L21

Logcat error : 
```
W PackageManager: Package com.android.webview signatures do not match previously installed version; ignoring!
```
Consequently, _Bromite System WebView_ is not installed, and stock _Android System WebView_ is stil present.

### Environment
* Device : Xiaomi Mi 9T "davinci"
* O/S : official LineageOS 17.1 with built-in microG (https://download.lineage.microg.org/davinci/), as supplied by the microG Project (https://microg.org/.)
* Magisk 21.1
* Webview_Switcher-7.1.1(4018).zip (patched) [*]
* additional Work profile, UserID=10 (by means of Insular, the Google-free version of Island : https://f-droid.org/en/packages/com.oasisfeng.island.fdroid/ )

[*] Note : to cope with some Webview Switcher bugs, I have applied the proposed patches in issues #23, #24, #25 and #26, which may be reflected in the slightly different scope of the attached logs.
Please note the exact identical error occurs with stock, unpatched Webview_Switcher-7.1.1(4018).zip

### Test permutations
This is reproducible in all test cases : 
* stock & patched Webview_Switcher-7.1.1(4018).zip
* on-line & off-line installation
* systemful TWRP & systemless Magisk
* (in off-line mode) with all current versions of BromiteWebView (v87.0.4280.81, v87.0.4280.106,v87.0.4280.131).

### Observations

1. webview.apk was successfully signed
2. WebviewOverlay.apk was installed in /product/overlay
3. /system/data/overlays.xml was successfully modified
4. with "BROWSER=true", Bromite is correctly installed

### Mitigation
The issue is mitigated by manually (systemlessly) installing a BromiteWebView apk as a system app in **/system/app** .

To keep the overview, I will post test methodology, diagnosis & log-files in a follow-up post.

**Comment by didierm** [comment]
To obtain a complete and concise overview of what works and what doesn't, I used the following methodological steps, and checked each and every result by reviewing the installed Webview version in : 
* _"Settings > System > Advanced > Developer > WebView implementation"_
* App Manager v2.5.20 (https://f-droid.org/en/packages/io.github.muntashirakon.AppManager/)



### step 0
On an almost pristine (a couple apps installed + Work profile) LineageOS17.1+microG+Magisk : 
* in recovery : adb sideload LOS17.1 and adb sideload Magisk 21.1
* reboot

_Result : stock **Android System WebView 86.0.4240.198** (as expected)_

### step 1
* for off-line installation, create /sdcard/WebviewSwitcher/arm64_SystemWebView.apk (v87.0.4280.81) and config.txt : 
```
OFFLINE=true
UNGOOGLED=false
BROMITE=true
VANILLA=false
BROWSER=false
```
* in MagiskManager 8.0.3, install Webview_Switcher-7.1.1(4018).zip (patched, see above) from local storage
* reboot

_Result : **Android System WebView 86.0.4240.198** (unsuccessful, should have been **Bromite System WebView 87.0.4280.106**)_
This is probably due to the abovementioned signature conflict.

### step 2
* construct a systemless system app installation of a previously downloaded BromiteWebView apk (v87.0.4280.106) : 
```
(in adb)
DIR="/data/adb/modules/bromitewebview/system/app/"
APP="BromiteSystemWebView"
VER="v87.0.4280.106"
install -D -m 0644 /sdcard/sys/misc/bromitewebview/${VER}_arm64_SystemWebView.apk $DIR/$APP/${APP}.apk
```
* reboot

_Result : **Bromite System WebView 87.0.4280.106** (successful systemless install)_
 
### step 3
* in F-Droid, add official Bromite repo (https://www.bromite.org/fdroid) and refresh repos
* update installed package "Bromite SystemWebView" v87.0.4280.106 to v87.0.4280.131
* do no reboot

_Result : **Bromite System WebView 87.0.4280.131** (successful systemless user update)_


Except for the webview.apk installation in service.sh, everything works as expected.

**Comment by didierm** [comment]
Log files : 

### step 0

* `dumpsys package com.android.webview` : [com.android.webview.dumpsys.out_0_orig.txt](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748693/com.android.webview.dumpsys.out_0_orig.txt)

### step 1

* `dumpsys package com.android.webview` : [com.android.webview.dumpsys.out_1_magisk1.txt](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748712/com.android.webview.dumpsys.out_1_magisk1.txt)

* Webview_Switcher-7.1.1(4018).zip module installation log **/sdcard/WebviewSwitcher/logs/install.log** : [install.log.txt](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748707/install.log.txt)
* filtered **logcat** (during reboot) : [logcat1.out.txt](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748708/logcat1.out.txt)
* **/data/adb/modules/bromitewebview/logs/** : [bromitewebview_module_logs.zip](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748688/bromitewebview_module_logs.zip)

* packages are present : 
```
davinci ~ # ll /data/user/*/ | egrep -i "web|brom"
drwx------  4 u0_a140        u0_a140        3488 2020-12-28 14:10 com.android.webview
drwxr-x--x  4 u0_a134        u0_a134        3488 2020-12-28 14:10 com.linuxandria.WebviewOverlay
drwx------  4 u10_a140           u10_a140           3488 2020-12-28 14:10 com.android.webview
drwxr-x--x  4 u10_a134           u10_a134           3488 2020-12-28 14:10 com.linuxandria.WebviewOverlay
```

### step 2
* `dumpsys package com.android.webview` : [com.android.webview.dumpsys.out_2_magisk2.txt](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748721/com.android.webview.dumpsys.out_2_magisk2.txt)

* filtered **logcat** (during reboot) : [logcat2.out.txt](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748722/logcat2.out.txt)


### step 3
* `dumpsys package com.android.webview` : [com.android.webview.dumpsys.out_3_fdroid.txt](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5748724/com.android.webview.dumpsys.out_3_fdroid.txt)

**Comment by didierm** [comment]
I tested today on a pristine (no microG) Samsung Tab S2 SM-T813 ("gts210vewifi") with LOS-17.1-unofficial and Magisk 21.1, with several permutations : clean | Magisk Busybox_osm0sis | secondary user profile , and in every case, the Webview Switcher module works as expected, offering the latest Bromite Webview.

**Comment by didierm** [comment]
Replicated with non-microG pristine lineage-17.1-20201202-nightly-davinci-signed.zip

**Comment by unixandria-xda** [comment]
Issue should be resolved in latest update by properly uninstalling any existing webview. Please reply if you still have issues
