### ISSUE TITLE
No work - OP 7T Pro

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/bromitewebview#28]
Just to want to report about this module does not work on my device (OP 7T Pro / Android 10).
It installs webkit and Bromite, however Webkit Test shows an obsolete Chrome webkit version that was intergrated in ROM.
Playmarket shows a possibility to update. I have tried to update using official webkit from Bromite project and from Playmarket - does not matter: still obsolete webkit version is shown.

**Comment by gjf** [comment]
More details: 
installation log
[install.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/5995838/install.log)
Webkit Info information:
![Screenshot_20210217-160118](https://user-images.githubusercontent.com/322186/108208842-9cf0ca00-713a-11eb-85c9-5d7574d801d0.jpg)
Playmarket wants to install update:
![Screenshot_20210217-160142](https://user-images.githubusercontent.com/322186/108208884-a5e19b80-713a-11eb-81e4-5b9e934b9009.jpg)
But when I try to install latest Bromite Webkit update - the system reports I have it already:
![Screenshot_20210217-160217](https://user-images.githubusercontent.com/322186/108208940-b98d0200-713a-11eb-9535-ff1a674f3536.jpg)

**Comment by androidacy** [comment]
Google webview, and it needing an update, are completely irrelevant for this module.

Closing as invalid.

**Comment by gjf** [comment]
Have you read it attentively? Your module did nothing - it did not install showing only system Google webkit.
And of course Google one wants to update.

**Comment by androidacy** [comment]
> Have you read it attentively? Your module did nothing - it did not install showing only system Google webkit.
> And of course Google one wants to update.

Nonetheless, you provided no userful information, and the system you are using has been explicitly confirmed working.

Please be patient and wait for 8.0 series beta releases, we're aware of similar bugs effecting other devices and have almost worked them out in internal testing.

**Comment by gjf** [comment]
I would be happy to present "useful" information - and actually presented bioth logs and screenshots.
Please let me know what exactly information you need.

**Comment by androidacy** [comment]
Try 8.0 beta 2 from [here](https://dl.androidacy.com/?ee=1&eeFolder=Magisk-Modules%2FWebviewSwitcher&eeListID=1(

**Comment by gjf** [comment]
For some reasons this beta did not install Bromite at all (with active internet).
Though it proceeds with all actions including deleting dalvik and changing sepolicy (for what?)
After reboot I didn't notice any new modules in Magisk. However trying to install this beta once again shows "previous version detected - uninstalling".

I think I'd better wait for release expecting more reliable code...

**Comment by androidacy** [comment]
> For some reasons this beta did not install Bromite at all (with active internet).
> Though it proceeds with all actions including deleting dalvik and changing sepolicy (for what?)
> After reboot I didn't notice any new modules in Magisk. However trying to install this beta once again shows "previous version detected - uninstalling".
> 
> I think I'd better wait for release expecting more reliable code...

Zip up /sdcard/Webview manager/logs and upload, please
