### ISSUE TITLE
Use fixed version of Bromite SystemWebView for each release

### ISSUE THREAD

**Issue by iyesin** [Magisk-Modules-Repo/bromitewebview#3]
Hello,

I believe that rolling model (download newest version of dependent package) is very bad combined with release model (since we have changelog and versions here). This makes harder to find/address bugs. May be it would not so bad idea to bundle fixed binary versions with this module. WDYT?

**Comment by alexa-v2** [comment]
This was the previous model

It was rejected because it increased the zip size to 400+MB,an unacceptable size

It is currently in consideration to allow to use an apk from sdcard but the details on how we will make sure it's the right apk and latest version is under review

**Comment by iyesin** [comment]
> It was rejected because it increased the zip size to 400+MB,an unacceptable size
Ok. This was about bundling. Obviously it's not an option.

What's about referencing exact version of SystemWebView component?

> It is currently in consideration to allow to use an apk from sdcard but the details on how we will make sure it's the right apk and latest version is unknown currently
What's about using "special" name for apk? Like `Yes_I_am_sure_I_want_to_install_this_bromite_systemwebview.apk`?

**Comment by alexa-v2** [comment]
Offline installs should work now; in the future I intend to add a config option for /sdcard/bromite/config which should contain a valid github release tag

**Comment by linuxandria** [comment]
TWRP installs should now work fine. In addtion, TWRP installs (shouldn't) check the version so that is no longer an issue. Closing, let me know if it doesn't work
