### ISSUE TITLE
wrong file name APK not same

### ISSUE THREAD

**Issue by zpcol** [Magisk-Modules-Repo/bromitewebview#30]
if bromite:
arm_SystemWebView.apk
arm64_SystemWebView.apk
x86_SystemWebView.apk

if ungoogled:
SystemWebView_arm.apk
SystemWebView_arm64.apk
SystemWebView_x86.apk

**Comment by zpcol** [comment]
![Screenshot_20210223_075257.jpg](https://user-images.githubusercontent.com/69243210/108789147-37726280-75ac-11eb-80f9-9e378ebf9476.jpg)

**Comment by androidacy** [comment]
Changed in latest betas so no longer valid.

Closing.
