### ISSUE TITLE
Webview Manager can't be installed

### ISSUE THREAD

**Issue by VerdghXeljior** [Magisk-Modules-Repo/bromitewebview#32]
Here's the log:
https://del.dog/gexamigran

Device: Xiaomi Mi 3C
ROM: exTHmui 10
Android: Q (10)
Magisk Version: v22.0

**Comment by africabloe** [comment]
Hello 
2 Redmi Note 4x phones with LineageOS 18.1 Android 11 have the same problem.
Installation failed.
[install.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/6188642/install.log)

Thank you

**Comment by ianmacd** [comment]
This is the problem:

```
+ wget -qO arm64_SystemWebView.apk.sha256.txt.tmp https://github.com/bromite/bromite/releas
es/download/89.0.4389.100/brm_89.0.4389.100.sha256.txt
wget: note: TLS certificate validation not implemented
+ grep arm64_SystemWebView.apk arm64_SystemWebView.apk.sha256.txt.tmp
+ rm -fr arm64_SystemWebView.apk.sha256.txt.tmp
+ sed -i s/arm64_SystemWebView.apk/BromiteWebview.apk/gi BromiteWebview.apk.sha256.txt
+ sha256sum -sc BromiteWebview.apk.sha256.txt
sha256sum: can't open 'BromiteWebview.apk': No such file or directory
```

Specifically, this command is failing to write the APK:

```
/data/adb/modules_update/bromitewebview/common/tools/aria2c-arm64 -x 16 -s 16 --async-dns --file-allocation=none --check-certificate=false --ca-certificate=/data/adb/modules_update/bromitewebview/ca-certificates.crt --quiet https://github.com/bromite/bromite/releases/download/89.0.4389.100/arm64_SystemWebView.apk
```

**Comment by coxackie** [comment]
Same problem in every single device I tried it on. Xiaomi, Moto and Samsung. Clearly there is a problem.

**Comment by androidacy** [comment]
Please test publicbeta3 from the filehost, thanks.

Seems android 10+ added some interesting sepolicy fuckery and magisk no longer works around it on its own.

**Comment by androidacy** [comment]
> This is the problem:
> 
> ```
> + wget -qO arm64_SystemWebView.apk.sha256.txt.tmp https://github.com/bromite/bromite/releas
> es/download/89.0.4389.100/brm_89.0.4389.100.sha256.txt
> wget: note: TLS certificate validation not implemented
> + grep arm64_SystemWebView.apk arm64_SystemWebView.apk.sha256.txt.tmp
> + rm -fr arm64_SystemWebView.apk.sha256.txt.tmp
> + sed -i s/arm64_SystemWebView.apk/BromiteWebview.apk/gi BromiteWebview.apk.sha256.txt
> + sha256sum -sc BromiteWebview.apk.sha256.txt
> sha256sum: can't open 'BromiteWebview.apk': No such file or directory
> ```
> 
> Specifically, this command is failing to write the APK:
> 
> ```
> /data/adb/modules_update/bromitewebview/common/tools/aria2c-arm64 -x 16 -s 16 --async-dns --file-allocation=none --check-certificate=false --ca-certificate=/data/adb/modules_update/bromitewebview/ca-certificates.crt --quiet https://github.com/bromite/bromite/releases/download/89.0.4389.100/arm64_SystemWebView.apk
> ```

You can thank selinux for that fuckery. Apparently magisk changed something about that since version 22000

**Comment by ianmacd** [comment]
> Please test publicbeta3 from the filehost, thanks.
> 
> Seems android 10+ added some interesting sepolicy fuckery and magisk no longer works around it on its own.

publicbeta3 installs fine now.

Is there a way to tell at a glance whether the Bromite webview is actually being used?

This logcat message seems to suggest another possible issue in the integration of the Bromite webview:

```
03-24 17:48:17.037  6804  7214 W AutofillManagerService: Ignoring not whitelisted compat package org.bromite.chromium
```

I saw something about whitelisting in the module installer script, so possibly that bit of code is not having the intended effect.

**Comment by androidacy** [comment]
> > Please test publicbeta3 from the filehost, thanks.
> > Seems android 10+ added some interesting sepolicy fuckery and magisk no longer works around it on its own.
> 
> publicbeta3 installs fine now and is working.
> 
> This logcat message seems to suggest another possible issue in the integration of the Bromite webview:
> 
> ```
> 03-24 17:48:17.037  6804  7214 W AutofillManagerService: Ignoring not whitelisted compat package org.bromite.chromium
> 03-24 17:48:17.038  6804  7214 W AutofillManagerService: Ignoring not whitelisted compat package org.bromite.bromite
> ```
> 
> I saw something about whitelisting in the module installer script, so possibly that bit of code is not having the intended effect.

Nah that's autofill shit with browser, up to bromite to fix that

**Comment by androidacy** [comment]
The whitelist fix is strictly for making Webview supported on any ROM

**Comment by coxackie** [comment]
can confirm that now it is working. Please make a new release soon - it would help a lot of other who have not realised there is an issue, or have not updated yet.

**Comment by africabloe** [comment]
Now its working. Thank you all
[WebviewManager-v8_1_0-publicbeta3.zip](https://dl.androidacy.com/wp-content/downloads/Magisk-Modules/WebviewManager/WebviewManager-v8_1_0-publicbeta3.zip)
 You can install the beta or to wait for WebviewManager-v8_1... Magisk release
