### ISSUE TITLE
[BUG] Unclear and rather worrisome post-installation message.

### ISSUE THREAD

**Issue by ianmacd** [Magisk-Modules-Repo/bromitewebview#33]
The following message, displayed when module installation completes, is really quite alarming:

```
Some OEM/Google things were remvoed during install, to avoid conflicts. You can reinstall them, but do not request support if you do.
```

Firstly, the message does not detail **what exactly** was removed, but the implication is that this was not done systemlessly.

I read through the installer code and didn't see anything happening outside of the Magisk-masked `/system`, but I may have missed something.

My point is, even if the module is performing all of its work systemlessly, that message is alarming and should be clarified.

And if the module really **is** uninstalling OEM/Google packages, it should really provide an itemised list of what was removed. Otherwise, telling the user "You can reinstall them" is a bit disingenuous. How can the user do that if he doesn't know what was removed?

**Comment by androidacy** [comment]
We use remove because it a) debloats them systemlessly and b) uninstalls the user package if present.

We also would like to avoid a wall of text during install, in addition to the debloating being dynamic in nature depending on user config and what's present on device, in addition to some based on API level.

**Comment by androidacy** [comment]
Theoretically if the user installs from recovery without magisk installed it should fall back to system install but that's kinda broken atm

**Comment by ianmacd** [comment]
> We use remove because it a) debloats them systemlessly and b) uninstalls the user package if present.
> 
> We also would like to avoid a wall of text during install, in addition to the debloating being dynamic in nature depending on user config and what's present on device, in addition to some based on API level.

That's a relief to hear.

I strongly suggest that you add the word "systemlessly" to the post-installation message when you detect installation via Magisk vs. in recovery:

```
Some OEM/Google things were systemlessly removed during installation to prevent conflicts.
```

With this knowledge, it doesn't matter what was removed. Disable the module and everything comes back. And if the user wants to know the details, he can just look in the module's directory on his device.

**Comment by androidacy** [comment]
Messaging changed from removed to debloated systemlessly in upcoming stable release. Closing.
