### ISSUE TITLE
[BUG] verification failed when trying to install bromite

### ISSUE THREAD

**Issue by chknatwork** [Magisk-Modules-Repo/bromitewebview#34]
Verification failed while installing Bromite System Webview

**To Reproduce**
1. Go to Magisk Modules
2. Click on Download Icon
3. Download successful but verification fails before it gives up.

**Expected behavior**
Bromite System Webview installed and selectable from Webview in Developer Options

**Desktop (please complete the following information):**
 - OS and Android version: Android 11
 - Device: OnePlus 7TPro
 - Version 11

**Additional context**
Can't install Bromite Webview using the module.

**Comment by fuzzyy0815** [comment]
I have the same Problem. Today first i removed that module without problems. 
Then i tryed to reinstall the module but it did not work. It cannot be reinstalled.

My Device: OnePlus 8 Pro
OS and Android version: Android 11


Here is the install log:

- Copying zip to temp directory
- Installing Webview_Manager-8.1.4(4046) (5).zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/esyld.ess/cache/flash/install.zip
  inflating: module.prop
*****************
Archive:  /data/user/0/esyld.ess/cache/flash/install.zip
  inflating: customize.sh
 Webview Manager 
 by Androidacy 
*****************
*******************
 Powered by Magisk 
*******************
mkdir: can't create directory '/sdcard/WebviewManager/logs/': File exists
- Logging verbosely to /sdcard/WebviewManager/logs
+ exec
- Extracting module files
- Removing old files
- Installing
ⓘ Android 11, API level 30, arch arm64 device detected
ⓘ Setting configs...
ⓘ No config found, using defaults
     (Only install bromite webview)
ⓘ Make sure if you want/need a custom setup to edit config.txt
ⓘ Testing internet connectivity
☑ Awesome, you have internet
ⓘ Detecting and debloating conflicting packages
ⓘ Webview install selected
ⓘ Checking whether this is a new install....
ⓘ No existing apk found for Bromite webview!
ⓘ Downloading Bromite webview, please be patient...
ⓘ Verifying Bromite webview files...
⚠ Verification failed, retrying download
ⓘ Checking whether this is a new install....
ⓘ Redownloading Bromite webview, attempt number 2, please be patient...
☑ Not a version upgrade! Using existing Bromite webview apk
ⓘ Verifying Bromite webview files...
⚠ Verification failed, retrying download
 
⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠
 
 Uh-oh, the installer encountered an issue!
 It's probably one of these reasons:
	 1) Installer is corrupt
	 2) You didn't follow instructions
	 3) You have an unstable internet connection
	 4) Your ROM is broken
	 5) There's a *tiny* chance we screwed up
 Please fix any issues and retry.
 If you feel this is a bug or need assistance, head to our telegram
 
⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠
 

! Installation failed

**Comment by fuzzyy0815** [comment]
Today, the install works!

**Comment by chknatwork** [comment]
> Today, the install works! 

Did anything change?

**Comment by nurullahsaeem** [comment]
I'm still having this problem

**Comment by androidacy** [comment]
You're using an extremely old version. Update your module.

**Comment by nurullahsaeem** [comment]
> You're using an extremely old version. Update your module.

I have tried installing the latest module from Magisk & also tried installing the one from your website. Both failed to connect. 😐
