### ISSUE TITLE
Webview gets reverted to stock after 2nd reboot.

### ISSUE THREAD

**Issue by Rtizer-9** [Magisk-Modules-Repo/bromitewebview#37]
The module installation goes completely fine without any error and I can see bromite webview in the app list and in developer options as well after the reboot but when I reboot again, it's gone.

If I flash the module again then it even makes use of the updated webview I installed later but after 2nd reboot the webview vanishes again.

Device: Redmi note 10 pro 
ROM   : Custom Rom LineageOS 18.1 (android 11) (unofficial)
Magisk : Canary 22104

[magisk_install_log_2021-05-10T12_32_30Z.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/6450591/magisk_install_log_2021-05-10T12_32_30Z.log)

**Comment by androidacy** [comment]
ROM specific bug. Doesn't happen on any lineage we've tried.
