### ISSUE TITLE
Recovery loop after install.

### ISSUE THREAD

**Issue by dweee** [Magisk-Modules-Repo/bromitewebview#4]
Bromite version

Version: Latest
Arch: arm64
Android version: 8.1, Latest official Lineage build.
Magisk version: Latest as of post.
Device model: Xiaomi Redmi Note 4

Is this bug about the SystemWebView?
Maybe?

Is the bug reproducible with latest version?
Yes

Can the bug be reproduced with corresponding Chromium version?
Installed BromiteWebView from Magisk.

Is the bug a crash?
Boot crash. As you've previously asked from another user in #2 and #3, I installed the module and [a gist to the error.log](https://gist.github.com/dweee/bd89f38a82391a6b6a0167c71ecacd03)

Describe the bug
Boot logo for about 10 minutes, reboot straight to the recovery menu

To Reproduce

1. Go to Magisk modules
2. Installed module
3. Agree to reboot
4. Get recovery loop (reboot into recovery.)

Expected behavior
See 4 in section above.

Sidenote: I didn't have Bromite installed beforehand, as the F-Droid repo wasn't working. Perhaps it could be related to that issue?

**Comment by alexa-v2** [comment]
All discussions relating to bootloops are going to #5
