### ISSUE TITLE
Bromite only installs on Work Profile

### ISSUE THREAD

**Issue by Ultracoolguy** [Magisk-Modules-Repo/bromitewebview#6]
I don't know where to post this, but since this is the only module I have issues with, I'll post it here.

 So, for some reason now, after updating to Magisk 20(maybe related, maybe not) Bromite only appears in my Shelter work profile. When I look in Settings>System>Developer Options>Webview Implementation, it says None, and when I click it, it appears Bromite. However, it's greyed out, saying "(Uninstalled for user Owner)". 

I don't know what else information would be useful, so I'll just leave the [bromitewebview-debug.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/3720655/bromitewebview-debug.log)

**Comment by alexa-v2** [comment]
Known issue

Upgrade to the beta version on Telegram - https://t.me/bromitewebview

**Comment by Ultracoolguy** [comment]
That fixed it. Thanks!
