### ISSUE TITLE
Disabled for user

### ISSUE THREAD

**Issue by DucAnhNguyen1997** [Magisk-Modules-Repo/bromitewebview#8]
Hi. I recently installed the Bromite Magisk module from the Magisk Manager app, restarted the phone immediately (took about 5 minutes), and tried to enable the WebView, only to find out that it was disabled, and the default Android WebView is gone. How can I enable it, and would installing the .apk file screwed my system (I want to keep it intact)?

**Comment by DucAnhNguyen1997** [comment]
Also, Chrome was installed on my device by default (system app). Was it the reason why it didn't work? If so, how can I circumvent that?

**Comment by robert6661** [comment]
I have got the same problem. I think you need to disable Chrome because on Android 7+ chrome comes with webview.

**Comment by alexa-v2** [comment]
Chrome does not play well with other webviews

If present it's automatically set as default. It **must** be disabled for this module to work correctly
