### ISSUE TITLE
Git conflicts need solved

### ISSUE THREAD

**Issue by Zackptg5** [Magisk-Modules-Repo/bromitewebview#9]
Just a heads up that there are a couple files with git conflicts that need solved and break the module:
customize.sh, module.prop, README.md

**Comment by alexa-v2** [comment]
I believe all of this is fixed locally I just haven't pushed yet

**Comment by alexa-v2** [comment]
@Zackptg5 fixed downstream - https://GitHub.com/alexa-v2/bromitewebview
